# Generated by Django 3.2.5 on 2021-08-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cr_short_name', models.TextField(default='')),
                ('cr_name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Forex',
            fields=[
                ('forex_id', models.IntegerField(default='', primary_key='True', serialize=False)),
                ('from_currency_id', models.IntegerField(default='')),
                ('to_currency_id', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Forex_quotes',
            fields=[
                ('forex_id', models.IntegerField(primary_key='True', serialize=False)),
                ('date', models.IntegerField(default='')),
                ('rate', models.IntegerField(default='')),
            ],
        ),
    ]
