# Generated by Django 3.2.5 on 2021-07-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=50, unique=True)),
                ('short_name', models.CharField(default='', max_length=3, unique=True)),
            ],
        ),
    ]
