# Generated by Django 3.2.5 on 2021-08-04 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='short_name',
        ),
        migrations.AddField(
            model_name='currency',
            name='date',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='forex_id',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='rate',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='simbol',
            field=models.CharField(default='', max_length=6, unique=True),
        ),
    ]
