# Generated by Django 3.2.5 on 2021-08-04 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210804_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='simbol',
            new_name='symbol',
        ),
    ]
