# Generated by Django 3.2.5 on 2021-08-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_currency_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='forex_id',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.CharField(default='', max_length=15),
        ),
    ]
