# Generated by Django 3.2.5 on 2021-08-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210804_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='forex_quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forex_id', models.CharField(default='', max_length=4)),
                ('date', models.CharField(default='', max_length=10)),
                ('rate', models.CharField(default='', max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
