# Generated by Django 3.2.5 on 2021-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210811_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex_quotes',
            name='date',
            field=models.DateField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='forex_quotes',
            name='forex_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='forex_quotes',
            name='rate',
            field=models.FloatField(default='', max_length=15),
        ),
    ]
