# Generated by Django 3.2.5 on 2021-08-14 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_currency_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex',
            name='from_currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_currency', to='api.currency'),
        ),
        migrations.AlterField(
            model_name='forex',
            name='to_currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_currency', to='api.currency'),
        ),
    ]
