# Generated by Django 3.2.5 on 2021-08-14 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210814_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex',
            name='forex_id',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='forex_quotes',
            name='date',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
        migrations.AlterField(
            model_name='forex_quotes',
            name='forex_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.forex'),
        ),
    ]
