# Generated by Django 3.2.5 on 2021-08-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210811_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='cr_short_name',
            field=models.TextField(default=''),
        ),
    ]
