# Generated by Django 3.2.5 on 2021-08-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_forex_quotes_forex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex_quotes',
            name='forex_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.forex'),
        ),
        migrations.AlterUniqueTogether(
            name='forex_quotes',
            unique_together={('forex_id', 'date')},
        ),
    ]
