# Generated by Django 3.2.5 on 2021-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_currency_cr_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forex_quotes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='forex_quotes',
            name='date',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='forex_quotes',
            name='forex_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='forex_quotes',
            unique_together=set(),
        ),
    ]
