# Generated by Django 3.2.5 on 2021-08-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210816_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex_quotes',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
