# Generated by Django 3.2.5 on 2021-08-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_forex_quotes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex_quotes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
