# Generated by Django 3.2.5 on 2021-09-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_currency_cr_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forex_quotes',
            name='forex_id',
            field=models.TextField(default=''),
        ),
    ]
